# Copyright (c) 2026, Optimus contributors
# For license information, please see license.txt

"""Tests for the HTML report-file save bypass (v0.5.2).

Frappe's File DocType runs ``validate_file_extension`` in before_insert
and throws ``FileTypeNotAllowed`` when the site's
System Settings → File Settings → Allowed File Extensions allowlist
doesn't include HTML. Admins frequently restrict that list to
business document types (CSV/PDF/PNG/etc.) and break the profiler's
report attachment.

Frappe's validator has a designed bypass:

    def validate_file_extension(self):
        # Only validate uploaded files, not generated by code/integrations.
        if not self.file_type or not frappe.request:
            return
        ...

analyze runs as a background RQ job in the normal case (no request
context, bypass fires). But when the site has the scheduler disabled,
analyze runs INLINE inside api.stop's HTTP handler frappe.request
is set, bypass doesn't fire, HTML report insert fails with
FileTypeNotAllowed.

_save_report_file wraps the insert in a narrow no-request context
so the validator's intended bypass path is hit. These tests lock in
that behavior.
"""

import inspect


def test_save_report_file_clears_request_around_insert():
	"""Source-inspection guard: _save_report_file must temporarily
	null out frappe.local.request before calling file_doc.insert().
	That's what triggers File.validate_file_extension's no-request
	bypass for code-generated files."""
	from optimus import analyze

	src = inspect.getsource(analyze._save_report_file)

	# The helper must set frappe.local.request = None before the
	# insert call.
	assert "frappe.local.request = None" in src, (
		"_save_report_file must temporarily null frappe.local.request "
		"before file_doc.insert() so File.validate_file_extension "
		"uses its no-request bypass for code-generated files. Pre-"
		"v0.5.2 the insert fired with a live request context and the "
		"validator threw FileTypeNotAllowed on HTML when the site's "
		"allowlist didn't include it."
	)

	# And MUST restore the original value afterwards.
	assert "frappe.local.request = saved_request" in src, (
		"_save_report_file must restore frappe.local.request after "
		"the insert so downstream request-handling code (e.g. the "
		"response builder in the inline-analyze caller) sees the "
		"real request object unchanged."
	)


def test_save_report_file_restore_is_in_finally():
	"""A failed insert must STILL restore frappe.local.request.
	Restoring only on success would leak None into downstream code
	when insert raises for any other reason."""
	from optimus import analyze

	src = inspect.getsource(analyze._save_report_file)
	# Check the restore is inside a finally block.
	# We grep for the literal sequence: try ... insert ... finally ... restore.
	stash_idx = src.find("saved_request = getattr(frappe.local")
	try_idx = src.find("try:", stash_idx)
	finally_idx = src.find("finally:", try_idx)
	restore_idx = src.find(
		"frappe.local.request = saved_request", finally_idx
	)
	assert stash_idx < try_idx < finally_idx < restore_idx, (
		"Restore of frappe.local.request must be in a finally so it "
		"runs regardless of whether insert succeeded. Current source "
		"doesn't match the expected try/finally structure."
	)


def test_save_report_file_preserves_original_error_handling():
	"""The outer try/except that logs failures to the Error Log and
	returns None must still wrap everything. Without this, a
	validator failure would crash the whole analyze pipeline
	instead of logging and continuing with no report attachment."""
	from optimus import analyze

	src = inspect.getsource(analyze._save_report_file)
	assert "frappe.log_error" in src
	assert "return None" in src
